config/routes.rb
Rails.application.routes.draw do
  resources :formula_pinturas
  resources :orden_trabajos
  resources :materias_primas

  get '/materias_primas/agregar' => "materias_primas#agregar"
  post '/materias_primas/agregar' => "materias_primas#agregar"
  get 'inventario/inventario' => "inventario#inventario"
  
  resources :clientes
  devise_for :users
  get 'inicio/inicio'

  root :to => 'inicio#inicio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/orden_trabajo.rb
class OrdenTrabajo < ApplicationRecord
   
end

app/controllers/orden_trabajos_controller.rb
class OrdenTrabajosController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_orden_trabajo, only: [:show, :edit, :update, :destroy]





  # GET /orden_trabajos
  # GET /orden_trabajos.json
  def index
    @orden_trabajos = OrdenTrabajo.all

  end




  # GET /orden_trabajos/1
  # GET /orden_trabajos/1.json
  def show
    respond_to do |format|
      format.html  
      format.json
      format.pdf {render template: 'orden_trabajos/reporte', pdf: 'reporte'}
    end
  end

  # GET /orden_trabajos/new
  def new
    @orden_trabajo = OrdenTrabajo.new
  end

  # GET /orden_trabajos/1/edit
  def edit
  end

  def calcula_tinetas!
    @orden_trabajo.tinetas = @orden_trabajo.formula_kilos / 24
  end

  def actualiza_fecha!
    @orden_trabajo.fecha = Time.now
  end

  def actualiza_materias!

    @formula = FormulaPintura.where( descripcion: @orden_trabajo.producto).first

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_1.to_s )
      @materia =  MateriasPrima.where( nombre:  @formula.materia_prima_1.to_s ).first
      nueva_cantidad =  @materia.cantidad -=  @formula.kg_materia_prima_1.to_i 
      if nueva_cantidad < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia.nombre} , necesitas almenos #{@formula.kg_materia_prima_1.to_i} y tienes #{@formula.kg_materia_prima_1.to_i + @materia.cantidad}")
        return false
      else
        @materia.update(cantidad: nueva_cantidad)
      end
    end
    
    if MateriasPrima.exists?( nombre:  @formula.materia_prima_2.to_s )
      @materia2 =  MateriasPrima.where( nombre:  @formula.materia_prima_2.to_s ).first
      nueva_cantidad2 =  @materia2.cantidad -=  @formula.kg_materia_prima_2.to_i
      if nueva_cantidad2 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia2.nombre} , necesitas almenos #{@formula.kg_materia_prima_2.to_i} y tienes #{@formula.kg_materia_prima_2.to_i + @materia2.cantidad}")
        return false
      else
          @materia2.update(cantidad: nueva_cantidad2)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_3.to_s )
      @materia3 =  MateriasPrima.where( nombre:  @formula.materia_prima_3.to_s ).first
      nueva_cantidad3 =  @materia3.cantidad -=  @formula.kg_materia_prima_3.to_i 
      if nueva_cantidad3 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia3.nombre} , necesitas almenos #{@formula.kg_materia_prima_3.to_i} y tienes #{@formula.kg_materia_prima_3.to_i + @materia3.cantidad}")
        return false
      else
          @materia3.update(cantidad: nueva_cantidad3)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_4.to_s )
      @materia4 =  MateriasPrima.where( nombre:  @formula.materia_prima_4.to_s ).first
      nueva_cantidad4 =  @materia4.cantidad -=  @formula.kg_materia_prima_4.to_i 
      if nueva_cantidad4 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia4.nombre} , necesitas almenos #{@formula.kg_materia_prima_4.to_i} y tienes #{@formula.kg_materia_prima_4.to_i + @materia4.cantidad}")
        return false
      else
          @materia4.update(cantidad: nueva_cantidad4)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_5.to_s )
      @materia5 =  MateriasPrima.where( nombre:  @formula.materia_prima_5.to_s ).first
      nueva_cantidad5 =  @materia5.cantidad -=  @formula.kg_materia_prima_5.to_i 
      if nueva_cantidad5 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia5.nombre} , necesitas almenos #{@formula.kg_materia_prima_5.to_i} y tienes #{@formula.kg_materia_prima_5.to_i + @materia5.cantidad}")
        return false
      else
          @materia5.update(cantidad: nueva_cantidad5)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_6.to_s )
      @materia6 =  MateriasPrima.where( nombre:  @formula.materia_prima_6.to_s ).first
      nueva_cantidad6 =  @materia6.cantidad -=  @formula.kg_materia_prima_6.to_i 
      if nueva_cantidad6 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia6.nombre} , necesitas almenos #{@formula.kg_materia_prima_6.to_i} y tienes #{@formula.kg_materia_prima_6.to_i + @materia6.cantidad}")
        return false
      else
          @materia6.update(cantidad: nueva_cantidad6)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_7.to_s )
      @materia7 =  MateriasPrima.where( nombre:  @formula.materia_prima_7.to_s ).first
      nueva_cantidad7 =  @materia7.cantidad -=  @formula.kg_materia_prima_7.to_i 
      if nueva_cantidad7 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia7.nombre} , necesitas almenos #{@formula.kg_materia_prima_7.to_i} y tienes #{@formula.kg_materia_prima_7.to_i + @materia7.cantidad}")
        return false
      else
          @materia7.update(cantidad: nueva_cantidad7)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_8.to_s )
      @materia8 =  MateriasPrima.where( nombre:  @formula.materia_prima_8.to_s ).first
      nueva_cantidad8 =  @materia8.cantidad -=  @formula.kg_materia_prima_8.to_i 
      if nueva_cantidad8 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia8.nombre} , necesitas almenos #{@formula.kg_materia_prima_8.to_i} y tienes #{@formula.kg_materia_prima_8.to_i + @materia8.cantidad}")
        return false
      else
          @materia8.update(cantidad: nueva_cantidad8)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_9.to_s )
      @materia9 =  MateriasPrima.where( nombre:  @formula.materia_prima_9.to_s ).first
      nueva_cantidad9 =  @materia9.cantidad -=  @formula.kg_materia_prima_9.to_i 
      if nueva_cantidad9 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia9.nombre} , necesitas almenos #{@formula.kg_materia_prima_9.to_i} y tienes #{@formula.kg_materia_prima_9.to_i + @materia9.cantidad}")
        return false
      else
          @materia9.update(cantidad: nueva_cantidad9)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_10.to_s )
      @materia10 =  MateriasPrima.where( nombre:  @formula.materia_prima_10.to_s ).first
      nueva_cantidad10 =  @materia10.cantidad -=  @formula.kg_materia_prima_10.to_i 
      if nueva_cantidad10 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia10.nombre} , necesitas almenos #{@formula.kg_materia_prima_10.to_i} y tienes #{@formula.kg_materia_prima_10.to_i + @materia10.cantidad}")
        return false
      else
          @materia10.update(cantidad: nueva_cantidad10)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_11.to_s )
      @materia11 =  MateriasPrima.where( nombre:  @formula.materia_prima_11.to_s ).first
      nueva_cantidad11 =  @materia11.cantidad -=  @formula.kg_materia_prima_11.to_i 
      if nueva_cantidad11 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia11.nombre} , necesitas almenos #{@formula.kg_materia_prima_11.to_i} y tienes #{@formula.kg_materia_prima_11.to_i + @materia11.cantidad}")
        return false
      else
          @materia11.update(cantidad: nueva_cantidad11)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_12.to_s )
      @materia12 =  MateriasPrima.where( nombre:  @formula.materia_prima_12.to_s ).first
      nueva_cantidad12 =  @materia12.cantidad -=  @formula.kg_materia_prima_12.to_i 
      if nueva_cantidad12 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia12.nombre} , necesitas almenos #{@formula.kg_materia_prima_12.to_i} y tienes #{@formula.kg_materia_prima_12.to_i + @materia12.cantidad}")
        return false
      else
          @materia12.update(cantidad: nueva_cantidad12)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_13.to_s )
      @materia13 =  MateriasPrima.where( nombre:  @formula.materia_prima_13.to_s ).first
      nueva_cantidad13 =  @materia13.cantidad -=  @formula.kg_materia_prima_13.to_i 
      if nueva_cantidad13 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia13.nombre} , necesitas almenos #{@formula.kg_materia_prima_13.to_i} y tienes #{@formula.kg_materia_prima_13.to_i + @materia13.cantidad}")
        return false
      else
          @materia13.update(cantidad: nueva_cantidad13)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_14.to_s )
      @materia14 =  MateriasPrima.where( nombre:  @formula.materia_prima_14.to_s ).first
      nueva_cantidad14 =  @materia14.cantidad -=  @formula.kg_materia_prima_14.to_i 
      if nueva_cantidad14 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia14.nombre} , necesitas almenos #{@formula.kg_materia_prima_14.to_i} y tienes #{@formula.kg_materia_prima_14.to_i + @materia14.cantidad}")
        return false
      else
          @materia14.update(cantidad: nueva_cantidad14)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_15.to_s )
      @materia15 =  MateriasPrima.where( nombre:  @formula.materia_prima_15.to_s ).first
      nueva_cantidad15 =  @materia15.cantidad -=  @formula.kg_materia_prima_15.to_i 
      if nueva_cantidad15 < 0 
        @orden_trabajo.errors.add(:gateway, "No hay suficiente materia: #{@materia15.nombre} , necesitas almenos #{@formula.kg_materia_prima_15.to_i} y tienes #{@formula.kg_materia_prima_15.to_i + @materia15.cantidad}")
        return false
      else
          @materia15.update(cantidad: nueva_cantidad15)
      end 
    end

    if MateriasPrima.exists?( nombre:  @formula.materia_prima_16.to_s )

app/helpers/orden_trabajos_helper.rb
module OrdenTrabajosHelper


    
end

app/views/orden_trabajos/_form.html.erb
<%= form_with(model: orden_trabajo, local: true) do |form| %>
  <% if orden_trabajo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(orden_trabajo.errors.count, "error") %> prohibited this orden_trabajo from being saved:</h2>

      <ul>
      <% orden_trabajo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pantonera %>
    <%= form.text_field :pantonera %>
  </div>

  <div class="field">
    <%= form.label :cliente %>

    <%= form.select(:cliente, Cliente.all.collect {|c| [ c.cliente_id, c.cliente_id ] } ) %>
  </div>

  <div class="field">
    <%= form.label :orden_de_compra %>
    <%= form.text_field :orden_de_compra %>
  </div>

  <div class="field">
    <%= form.label :producto %>
    <%= form.select(:producto, FormulaPintura.all.collect {|f| [ f.descripcion, f.descripcion ] } ) %>
  </div>

  <div class="field">
    <%= form.label :grano %>
   <%= form.select(:grano,  options_for_select(  [['Extra fino', 'Extra fino '], ['Fino', 'Fino'], ['Medio', 'Medio'], ['Grueso', 'Grueso'], ['No aplica', 'No aplica'] ]  )) %>
   
  </div>

  <div class="field">
    <%= form.label :formula_kilos %>
    <%= form.text_field :formula_kilos %>
  </div>

  <div class="field">
    <%= form.label :muestra_color %>
    <%= form.check_box :muestra_color %>
  </div>

  <div class="field">
    <%= form.label :colorista_a_cargo %>
    <%= form.text_field :colorista_a_cargo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orden_trabajos/edit.html.erb
<h1>Editing Orden Trabajo</h1>

<%= render 'form', orden_trabajo: @orden_trabajo %>

<%= link_to 'Show', @orden_trabajo %> |
<%= link_to 'Back', orden_trabajos_path %>

app/views/orden_trabajos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orden Trabajos</h1>



<table>
  <thead>
    <tr>
      <th>Pantonera</th>
      <th>Cliente</th>
      <th>Orden de compra</th>
      <th>Producto</th>
      <th>Grano</th>
      <th>Formula kilos</th>
      <th>Tinetas</th>
      <th>Fecha</th>
      <th>Muestra color</th>
      <th>Colorista a cargo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orden_trabajos.each do |orden_trabajo| %>
      <tr>
        <td><%= orden_trabajo.pantonera %></td>
        <td><%= orden_trabajo.cliente %></td>
        <td><%= orden_trabajo.orden_de_compra %></td>
        <td><%= orden_trabajo.producto %></td>
        <td><%= orden_trabajo.grano %></td>
        <td><%= orden_trabajo.formula_kilos %></td>
        <td><%= orden_trabajo.tinetas %></td>
        <td><%= orden_trabajo.fecha %></td>
        <td><%= orden_trabajo.muestra_color %></td>
        <td><%= orden_trabajo.colorista_a_cargo %></td>
        <td><%= link_to "pdf", orden_trabajo_url(orden_trabajo, format: :pdf)  %></td>
        <td><%= link_to 'Ver', orden_trabajo %></td>
        <td><%= link_to 'Editar', edit_orden_trabajo_path(orden_trabajo) %></td>
        <td><%= link_to 'Eliminar', orden_trabajo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Orden Trabajo', new_orden_trabajo_path %>

app/views/orden_trabajos/new.html.erb
<h1>New Orden Trabajo</h1>

<%= render 'form', orden_trabajo: @orden_trabajo %>

<%= link_to 'Atras', orden_trabajos_path %>

app/views/orden_trabajos/reporte.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>

<style>
  table {
    width: 100%;
    padding: 10px 0;
    font-family:'Arial';
    text-transform: uppercase;
    font-size:15px;

  }
  h1{
     font-family:'Arial';
    width:100%;
       clear:both;
    font-size:19px;
   border: 1px solid black;
    padding:5px;
    background: #536ae0;
     text-align:center;
    color: white;
    margin-bottom:0px;
  }
  table th{
    border: 1px solid black;
    padding:5px;
    background: #536ae0;
     text-align:center;
    color: white;
    margin:0!important;
  }
   table td{
   margin: 0;
     margin:0!important;

   padding: 3px;
    border: 1px solid black;
    text-align:center;
  }
img{
  float:left;
}
h5{
  float:right;
      font-family:'Arial';
      clear:both;
}
</style>

<% @formula = FormulaPintura.where(descripcion: @orden_trabajo.producto).first %>
<% @formula.formula_kg = @orden_trabajo.formula_kilos %>
<% calculo_kg_formula(@formula) %>
<% calculo_costo(@formula) %>
        <%= wicked_pdf_image_tag 'logoandescolor.png' %>
       
        <h5> Fecha de emisión de reporte: <%= Time.now %></h5>
<table class="ot" cellspacing="0">
 <tr>
    <h1>OT<%= @orden_trabajo.id %> </h1>
 </tr>
  <tr>
    <td>Pantonera:</td>
    <td><%= @orden_trabajo.pantonera %></td> 
  </tr>
  <tr>
    <td>Cliente</td>
    <td><%= @orden_trabajo.cliente %></td> 
  </tr>
  <tr>
    <td>Orden de compra:</td>
    <td><%= @orden_trabajo.orden_de_compra %></td>
  </tr>
  <tr>
    <td>Producto</td>
    <td><%= @orden_trabajo.grano  %></td>
    
  </tr>
  <tr>
    <td> Formula </td>
    <td> <%= @orden_trabajo.producto %></td>
  </tr>
  <tr>
    <td> Formula kilos</td>
    <td>  <%= @orden_trabajo.formula_kilos %></td>
  </tr>
  <tr>
    <td>Tinetas</td>
    <td>  <%= @orden_trabajo.tinetas %></td>
  </tr>
   <tr>
    <td>Fecha de produccion:</td>
    <td>  <%= @orden_trabajo.fecha %></td>
  </tr>
  <tr>
    <td>Muestra color</td>
    <td><%= @orden_trabajo.muestra_color %></td>
  </tr>
  <tr>
    <td>Colorista a cargo:</td>
    <td><%= @orden_trabajo.colorista_a_cargo %> </td>
  </tr>
  <tr>
    <td>Formula </td>
    <td><%= @formula.descripcion %></td>
  </tr>
  <tr>
    <td> Fomulas kilos</td> 
    <td>  <%= @orden_trabajo.formula_kilos %></td>
  </tr>
</table>

<table class="formula" cellspacing="0">
  <tr>
    <th>Item </th>
    <th> Materia Prima </th>
    <th> % </th>
    <th> kg </th>
  </tr>
  <tr>
    <td> 1 </td>
    <td> <%= @formula.materia_prima_1 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_1 %></td>
    <td> <%= @formula.kg_materia_prima_1.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 2 </td>
    <td> <%= @formula.materia_prima_2 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_2 %></td>
    <td> <%= @formula.kg_materia_prima_2.to_f.round(2)  %> </td>
  </tr>
    <tr>
    <td> 3 </td>
    <td> <%= @formula.materia_prima_3 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_3 %></td>
    <td> <%= @formula.kg_materia_prima_3.to_f.round(2) %> </td>
  </tr>
    <tr>
    <td> 4 </td>
    <td> <%= @formula.materia_prima_4 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_4 %></td>
    <td> <%= @formula.kg_materia_prima_4.to_f.round(2) %> </td>
  </tr>
    <tr>
    <td> 5 </td>
    <td> <%= @formula.materia_prima_5 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_5 %></td>
    <td> <%= @formula.kg_materia_prima_5.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 6 </td>
    <td> <%= @formula.materia_prima_6 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_6 %></td>
    <td> <%= @formula.kg_materia_prima_6.to_f.round(2) %> </td>
  </tr>
    <tr>
    <td> 7 </td>
    <td> <%= @formula.materia_prima_7 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_7 %></td>
    
  </tr>
    <tr>
    <td> 8 </td>
    <td> <%= @formula.materia_prima_8 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_8 %></td>
    <td> <%= @formula.kg_materia_prima_8.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 9 </td>
    <td> <%= @formula.materia_prima_9 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_9 %></td>
    <td> <%= @formula.kg_materia_prima_9.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 10 </td>
    <td> <%= @formula.materia_prima_10 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_10 %></td>
    <td> <%= @formula.kg_materia_prima_10.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 11 </td>
    <td> <%= @formula.materia_prima_11 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_11 %></td>
    <td> <%= @formula.kg_materia_prima_11.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 12 </td>
    <td> <%= @formula.materia_prima_12 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_12 %></td>
    <td> <%= @formula.kg_materia_prima_12.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 13 </td>
    <td> <%= @formula.materia_prima_13 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_13 %></td>
    <td> <%= @formula.kg_materia_prima_13.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 14 </td>
    <td> <%= @formula.materia_prima_14 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_14 %></td>
    <td> <%= @formula.kg_materia_prima_14.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 15 </td>
    <td> <%= @formula.materia_prima_15 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_15 %></td>
    <td> <%= @formula.kg_materia_prima_15.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 16 </td>
    <td> <%= @formula.materia_prima_16 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_16 %></td>
    <td> <%= @formula.kg_materia_prima_16.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 17 </td>
    <td> <%= @formula.materia_prima_17 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_17 %></td>
    <td> <%= @formula.kg_materia_prima_17.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 18 </td>
    <td> <%= @formula.materia_prima_18 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_18 %></td>
    <td> <%= @formula.kg_materia_prima_18.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 19 </td>
    <td> <%= @formula.materia_prima_19 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_19 %></td>
    <td> <%= @formula.kg_materia_prima_19.to_f.round(2) %> </td>

  </tr>
    <tr>
    <td> 20 </td>
    <td> <%= @formula.materia_prima_20 %> </td>
    <td> <%= @formula.porcentaje_materia_prima_20 %></td>
    <td> <%= @formula.kg_materia_prima_20.to_f.round(2) %> </td>
  </tr>
  <tr>
  <td style="background: #4b87c7;color:white;">Totales</td>
  <td></td>
  <td><%= porcentaje_total_formula_calc(@formula) %></td>
    <td><%= kilos_total_formula_calc(@formula) %></td>
  </tr>
</table>



</body>
</html>

app/views/orden_trabajos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pantonera:</strong>
  <%= @orden_trabajo.pantonera %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @orden_trabajo.cliente %>
</p>

<p>
  <strong>Orden de compra:</strong>
  <%= @orden_trabajo.orden_de_compra %>
</p>

<p>
  <strong>Producto:</strong>
  <%= @orden_trabajo.producto %>
</p>

<p>
  <strong>Grano:</strong>
  <%= @orden_trabajo.grano %>
</p>

<p>
  <strong>Formula kilos:</strong>
  <%= @orden_trabajo.formula_kilos %>
</p>

<p>
  <strong>Tinetas:</strong>
  <%= @orden_trabajo.tinetas %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @orden_trabajo.fecha %>
</p>

<p>
  <strong>Muestra color:</strong>
  <%= @orden_trabajo.muestra_color %>
</p>

<p>
  <strong>Colorista a cargo:</strong>
  <%= @orden_trabajo.colorista_a_cargo %>
</p>

<%= link_to 'Edit', edit_orden_trabajo_path(@orden_trabajo) %> |
<%= link_to 'Back', orden_trabajos_path %>