config/routes.rb
Rails.application.routes.draw do
  resources :formula_pinturas
  resources :orden_trabajos
  resources :materias_primas

  get '/materias_primas/agregar' => "materias_primas#agregar"
  post '/materias_primas/agregar' => "materias_primas#agregar"
  get 'inventario/inventario' => "inventario#inventario"
  
  resources :clientes
  devise_for :users
  get 'inicio/inicio'

  root :to => 'inicio#inicio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/formula_pintura.rb
class FormulaPintura < ApplicationRecord
    
end

app/helpers/formula_pinturas_helper.rb
module FormulaPinturasHelper

end

app/views/formula_pinturas/_form.html.erb
<%= form_with(model: formula_pintura, local: true) do |form| %>
  <% if formula_pintura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formula_pintura.errors.count, "error") %> prohibited this formula_pintura from being saved:</h2>

      <ul>
      <% formula_pintura.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <div class="field">
    <%= form.label 'Nombre' %>
    <%= form.text_field :descripcion %>
  </div>

  <div class="field">

  <div class="field hide">
    <%= form.label :formula_kg %>
    <%= form.text_field :formula_kg, value: 0  %>
  </div>

  <div class="field">
    <%= form.label :codigo_formula %>
    <%= form.text_field :codigo_formula %>
  </div>

 

  <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_1 %>
      <%= form.select(:materia_prima_1, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>



    <div class="field">
      <%= form.label :porcentaje_materia_prima_1 %>
      <%= form.text_field :porcentaje_materia_prima_1 %>
    </div>
   
   


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_2 %>
      <%= form.select(:materia_prima_2, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

  
    <div class="field">
      <%= form.label :porcentaje_materia_prima_2 %>
      <%= form.text_field :porcentaje_materia_prima_2 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_3 %>
      <%= form.select(:materia_prima_3, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>



    <div class="field">
      <%= form.label :porcentaje_materia_prima_3 %>
      <%= form.text_field :porcentaje_materia_prima_3 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_4 %>
      <%= form.select(:materia_prima_4, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_4 %>
      <%= form.text_field :porcentaje_materia_prima_4 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_5 %>
      <%= form.select(:materia_prima_5, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_5 %>
      <%= form.text_field :porcentaje_materia_prima_5 %>
    </div>

 
  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_6 %>
      <%= form.select(:materia_prima_6, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_6 %>
      <%= form.text_field :porcentaje_materia_prima_6 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_7 %>
      <%= form.select(:materia_prima_7, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_7 %>
      <%= form.text_field :porcentaje_materia_prima_7 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_8 %>
      <%= form.select(:materia_prima_8, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_8 %>
      <%= form.text_field :porcentaje_materia_prima_8 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_9 %>
      <%= form.select(:materia_prima_9, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_9 %>
      <%= form.text_field :porcentaje_materia_prima_9 %>
    </div>



  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_10 %>
      <%= form.select(:materia_prima_10, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_10 %>
      <%= form.text_field :porcentaje_materia_prima_10 %>
    </div>


 
  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_11 %>
      <%= form.select(:materia_prima_11, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_11 %>
      <%= form.text_field :porcentaje_materia_prima_11 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_12 %>
      <%= form.select(:materia_prima_12, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_12 %>
      <%= form.text_field :porcentaje_materia_prima_12 %>
    </div>


  
  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_13 %>
      <%= form.select(:materia_prima_13, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_13 %>
      <%= form.text_field :porcentaje_materia_prima_13 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_14 %>
      <%= form.select(:materia_prima_14, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_14 %>
      <%= form.text_field :porcentaje_materia_prima_14 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_15 %>
      <%= form.select(:materia_prima_15, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_15 %>
      <%= form.text_field :porcentaje_materia_prima_15 %>
    </div>

  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_16 %>
      <%= form.select(:materia_prima_16, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_16 %>
      <%= form.text_field :porcentaje_materia_prima_16 %>
    </div>


  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_17 %>
      <%= form.select(:materia_prima_17, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_17 %>
      <%= form.text_field :porcentaje_materia_prima_17 %>
    </div>

 
  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_18 %>
      <%= form.select(:materia_prima_18, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_18 %>
      <%= form.text_field :porcentaje_materia_prima_18 %>
    </div>
 
  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_19 %>
      <%= form.select(:materia_prima_19, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_19 %>
      <%= form.text_field :porcentaje_materia_prima_19 %>
    </div>

  
  </div>
    <div class="materia_formula_edit">
    <div class="field">
      <%= form.label :materia_prima_20 %>
      <%= form.select(:materia_prima_20, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } .push(["No Aplica",nil]) ) %>
    </div>


    <div class="field">
      <%= form.label :porcentaje_materia_prima_20 %>
      <%= form.text_field :porcentaje_materia_prima_20 %>
    </div>
    
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formula_pinturas/edit.html.erb
<h1>Editing Formula Pintura</h1>

<%= render 'form', formula_pintura: @formula_pintura %>

<%= link_to 'Ver formula', @formula_pintura %> |
<%= link_to 'Atras', formula_pinturas_path %>

app/views/formula_pinturas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Formula Pinturas</h1>

<table>
  <thead>
    <tr>

      <th>Nombre</th>
      <th>Codigo formula</th>

  
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formula_pinturas.each do |formula_pintura| %>
      <tr>
         <td><%= formula_pintura.descripcion %></td>
        <td><%= formula_pintura.codigo_formula %></td>
       
        <td  class="boton"><%= link_to "pdf", formula_pintura_path(formula_pintura, format: :pdf)  %></td>
        <td class="boton"><%= link_to 'Ver', formula_pintura %></td>
        <td class="boton"><%= link_to 'Editar', edit_formula_pintura_path(formula_pintura) %></td>
        <td class="boton"><%= link_to 'Eliminar', formula_pintura, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Formula', new_formula_pintura_path %>

app/views/formula_pinturas/new.html.erb
<h1>Crear nueva formula</h1>
<p> Los decimales deben ingresarse con puntos (.), los porcentajes deben incluir solo el número, sin el simbolo '%' </p>
<script> 
    $(".materia_formula_edit select").val("No aplica");
</script>
<%= render 'form', formula_pintura: @formula_pintura %>

<%= link_to 'Atras', formula_pinturas_path %>

app/views/formula_pinturas/show.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(model: @formula_pintura, local: true) do |form| %>

<h2><%= @formula_pintura.descripcion %></h2>
<br>
   <div class="field">
    <%= form.label 'Nombre' %>
    <%= form.text_field :descripcion, disabled: true  %>
  </div>

 <!-- <div class="field"> -->
  <!--    <%= form.label :dolar_considerado %> -->
  <!--   <%= form.text_field :dolar_considerado , disabled: true %>  -->
 <!-- </div> -->


  <div class="field">
    <%= form.label :codigo_formula %>
    <%= form.text_field :codigo_formula , disabled: true %>
  </div>

 

  <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_1 %>
      <%= form.select(:materia_prima_1, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] }) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_1 %>
      <%= form.text_field :costo_kg_materia_prima_1 , disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_1 %>
      <%= form.text_field :porcentaje_materia_prima_1 , disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_2 %>
      <%= form.select(:materia_prima_2, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_2 %>
      <%= form.text_field :costo_kg_materia_prima_2 , disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_2 %>
      <%= form.text_field :porcentaje_materia_prima_2, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_3 %>
      <%= form.select(:materia_prima_3, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_3 %>
      <%= form.text_field :costo_kg_materia_prima_3, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_3 %>
      <%= form.text_field :porcentaje_materia_prima_3, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_4 %>
      <%= form.select(:materia_prima_4, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_4 %>
      <%= form.text_field :costo_kg_materia_prima_4, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_4 %>
      <%= form.text_field :porcentaje_materia_prima_4, disabled: true %>
    </div>
  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_5 %>
      <%= form.select(:materia_prima_5, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_5 %>
      <%= form.text_field :costo_kg_materia_prima_5, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_5 %>
      <%= form.text_field :porcentaje_materia_prima_5, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_6 %>
      <%= form.select(:materia_prima_6, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_6 %>
      <%= form.text_field :costo_kg_materia_prima_6, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_6 %>
      <%= form.text_field :porcentaje_materia_prima_6, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_7 %>
      <%= form.select(:materia_prima_7, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_7 %>
      <%= form.text_field :costo_kg_materia_prima_7, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_7 %>
      <%= form.text_field :porcentaje_materia_prima_7, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_8 %>
      <%= form.select(:materia_prima_8, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_8 %>
      <%= form.text_field :costo_kg_materia_prima_8, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_8 %>
      <%= form.text_field :porcentaje_materia_prima_8, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_9 %>
      <%= form.select(:materia_prima_9, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_9 %>
      <%= form.text_field :costo_kg_materia_prima_9, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_9 %>
      <%= form.text_field :porcentaje_materia_prima_9, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_10 %>
      <%= form.select(:materia_prima_10, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_10 %>
      <%= form.text_field :costo_kg_materia_prima_10, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_10 %>
      <%= form.text_field :porcentaje_materia_prima_10, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_11 %>
      <%= form.select(:materia_prima_11, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_11 %>
      <%= form.text_field :costo_kg_materia_prima_11, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_11 %>
      <%= form.text_field :porcentaje_materia_prima_11, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_12 %>
      <%= form.select(:materia_prima_12, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_12 %>
      <%= form.text_field :costo_kg_materia_prima_12, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_12 %>
      <%= form.text_field :porcentaje_materia_prima_12, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_13 %>
      <%= form.select(:materia_prima_13, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_13 %>
      <%= form.text_field :costo_kg_materia_prima_13, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_13 %>
      <%= form.text_field :porcentaje_materia_prima_13, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_14 %>
      <%= form.select(:materia_prima_14, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_14 %>
      <%= form.text_field :costo_kg_materia_prima_14, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_14 %>
      <%= form.text_field :porcentaje_materia_prima_14, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_15 %>
      <%= form.select(:materia_prima_15, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_15 %>
      <%= form.text_field :costo_kg_materia_prima_15, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_15 %>
      <%= form.text_field :porcentaje_materia_prima_15, disabled: true %>
    </div>

  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_16 %>
      <%= form.select(:materia_prima_16, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_16 %>
      <%= form.text_field :costo_kg_materia_prima_16, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_16 %>
      <%= form.text_field :porcentaje_materia_prima_16, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_17 %>
      <%= form.select(:materia_prima_17, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_17 %>
      <%= form.text_field :costo_kg_materia_prima_17, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_17 %>
      <%= form.text_field :porcentaje_materia_prima_17, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_18 %>
      <%= form.select(:materia_prima_18, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_18 %>
      <%= form.text_field :costo_kg_materia_prima_18, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_18 %>
      <%= form.text_field :porcentaje_materia_prima_18, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_19 %>
      <%= form.select(:materia_prima_19, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_19 %>
      <%= form.text_field :costo_kg_materia_prima_19, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_19 %>
      <%= form.text_field :porcentaje_materia_prima_19, disabled: true %>
    </div>


  </div>
    <div class="materia_formula_show">
    <div class="field">
      <%= form.label :materia_prima_20 %>
      <%= form.select(:materia_prima_20, MateriasPrima.all.collect {|m| [ m.nombre, m.nombre ] } ) %>
    </div>

    <div class="field">
      <%= form.label :costo_kg_materia_prima_20 %>
      <%= form.text_field :costo_kg_materia_prima_20, disabled: true %>
    </div>

    <div class="field">
      <%= form.label :porcentaje_materia_prima_20 %>
      <%= form.text_field :porcentaje_materia_prima_20, disabled: true %>
    </div>


  </div>


<% end %>

</p>

<%= link_to 'Edit', edit_formula_pintura_path(@formula_pintura) %> |
<%= link_to 'Back', formula_pinturas_path %>