config/routes.rb
Rails.application.routes.draw do
  resources :formula_pinturas
  resources :orden_trabajos
  resources :materias_primas

  get '/materias_primas/agregar' => "materias_primas#agregar"
  post '/materias_primas/agregar' => "materias_primas#agregar"
  get 'inventario/inventario' => "inventario#inventario"
  
  resources :clientes
  devise_for :users
  get 'inicio/inicio'

  root :to => 'inicio#inicio'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andes color v11</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
 <!-- Navigation -->
    <nav class="navbar  navbar-fixed-top" role="navigation" style="overflow-y: scroll;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                  <%= link_to "Andes color", root_url, class: "inicio-link" %>
            <div class="logo">
              
                <img src="<%= asset_path 'logoandescolor.png' %>">
            </div>
           </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">

                  
                    <li>
                        <i class="fas fa-briefcase"></i>
                        <%= link_to "Ordenes de trabajo" , orden_trabajos_path %>
                    </li>
                         <li class="subitem_menu">
                            <i class="fas fa-plus"></i>
                            <%= link_to "Agregar" , new_orden_trabajo_path %>
                        </li>
                    <li>
                        <i class="fas fa-briefcase"></i>
                        <%= link_to "Formulas" , formula_pinturas_path %>
                    </li>
                         <li class="subitem_menu">
                            <i class="fas fa-plus"></i>
                            <%= link_to "Agregar" , new_formula_pintura_path %>
                        </li>
                    <li>
                        <i class="fas fa-paint-roller"></i>
                        <%= link_to "Inventario" , inventario_inventario_path %>
                    </li>
                         <li  class="subitem_menu">
                            <i class="fas fa-paint-roller"></i>
                            <%= link_to "Materias" , materias_primas_path %>
                        </li>
                        <li class="subitem_menu">
                            <i class="fas fa-plus"></i>
                            <%= link_to "Agregar" , new_materias_prima_path %>
                        </li>
                        <li class="subitem_menu">
                            <i class="fas fa-sync-alt"></i>
                            <%= link_to "Actualizar" , materias_primas_agregar_path %>
                        </li>
                    <li>
                        <i class="fas fa-user"></i>
                        <%= link_to "Clientes" , clientes_path %>
                    </li>
                        <li class="subitem_menu">
                            <i class="fas fa-plus"></i>
                            <%= link_to "Agregar" , new_cliente_path %>
                        </li>

                   <% if user_signed_in? %>
                    <li>
                     <a> Usuario actual: <%= current_user.email %></a>
                    </li>
                    <li>
                        <i class="fas fa-user"></i>
                        <%= link_to('Salir', destroy_user_session_path, method: :delete, confirm: "Estas seguro?" ) %>    
                    </li>
                   <% else%>
                    <li>
                      <%= link_to "Ingresa a tu cuenta" , user_session_path %>
                    </li>
                 
                   <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container wrapper-app">

        <div class="row">
            <div class="col-lg-12 text-center">
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
                <% if user_signed_in? || request.env['REQUEST_URI'] == "/users/sign_in" || request.env['REQUEST_URI'] == "/users/sign_up" %>
                    <%= yield %>
                <% else %>
                  <h2>Debes iniciar sesion para utilizar la aplicacion</h2>
                <% end %>
            </div>
        </div>
        <!-- /.row -->

    </div>

    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js"/>
  </body>
</html>